// This file is generated by Slice Machine. Update with care!

import HeroVideo from './HeroVideo';
import NavigationBar from './NavigationBar';

export {
	HeroVideo,
	NavigationBar,
};

export const components = {
	hero_video: HeroVideo,
	navigation_bar: NavigationBar,
};
