// Code generated by Slice Machine. DO NOT EDIT.

import Cards from './Cards';
import CardsWithForm from './CardsWithForm';
import Cta from './Cta';
import Fees from './Fees';
import FullImage from './FullImage';
import FundGrid from './FundGrid';
import HeroGradient from './HeroGradient';
import HeroIdeas from './HeroIdeas';
import HeroImage from './HeroImage';
import HeroProducts from './HeroProducts';
import HeroSimple from './HeroSimple';
import HeroValues from './HeroValues';
import HeroVideo from './HeroVideo';
import ItemNavBar from './ItemNavBar';
import NavigationBar from './NavigationBar';
import PeopleSlider from './PeopleSlider';
import PostCta from './PostCta';
import PostsList from './PostsList';
import RichText from './RichText';
import StoreButtonsCta from './StoreButtonsCta';
import Tabs from './Tabs';

export {
	Cards,
	CardsWithForm,
	Cta,
	Fees,
	FullImage,
	FundGrid,
	HeroGradient,
	HeroIdeas,
	HeroImage,
	HeroProducts,
	HeroSimple,
	HeroValues,
	HeroVideo,
	ItemNavBar,
	NavigationBar,
	PeopleSlider,
	PostCta,
	PostsList,
	RichText,
	StoreButtonsCta,
	Tabs,
};

export const components = {
	cards: Cards,
	cards_with_form: CardsWithForm,
	cta: Cta,
	fees: Fees,
	full_image: FullImage,
	fund_grid: FundGrid,
	hero_gradient: HeroGradient,
	hero_ideas: HeroIdeas,
	hero_image: HeroImage,
	hero_products: HeroProducts,
	hero_simple: HeroSimple,
	hero_values: HeroValues,
	hero_video: HeroVideo,
	item: ItemNavBar,
	navigation_bar: NavigationBar,
	people_slider: PeopleSlider,
	post_cta: PostCta,
	posts_list: PostsList,
	rich_text: RichText,
	store_buttons_cta: StoreButtonsCta,
	tabs: Tabs,
};
